# Generated by Django 4.2.4 on 2023-08-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
